[package]
name = "decision_tree"
version = "0.1.0"
authors = ["Pearce Keesling <keeslinp@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
regex = "1.1.2"
rand = "0.6.5"
lazy_static = "1.3.0"
itertools = "0.8.0"
